import random
import json
import requests
from src.api_secrets import gemini_api_key
# Name: Kush Patel
# Project Description: This program generates a markdown resume by combining a personal description with
#                      a randomly selected job description from rapid_jobs2.json. The markdown resume is
#                      generated by prompting the Gemini AI model to create a markdown resume based on this information.

# Note to self for github yaml command for pytest: python -m pytest tests/*


# Function to get a random job listing from the JSON file
def get_random_json_object():
    with open('../rapid_jobs2.json', 'r') as f:
        json_objects = []
        for line in f:
            # Read each line in rapid_jobs2.json file as a JSON object
            json_objects.append(json.loads(line))
        # Select a random section from the JSON list
        random_job_section = random.choice(json_objects)
        # Select a random job within the chosen section
        random_job = random.choice(random_job_section)
    return random_job


def main():
    # Get the API key from the api_secrets file to access Google's Gemini AI model
    key = gemini_api_key
    # Using the random_json_object(), get a random job and then extract the job description from the job.
    job_json_random = get_random_json_object()
    job_description = job_json_random["description"]

    # Personal information to be included in the resume
    personal_info = ("My name is Kush Patel. I am a computer science major studying at Bridgewater State University (BSU),"
                     " I am driven by a desire to innovate and problem solve. I am graduating from the BSU on May, 2025. "
                     "Some important courses I have completed at BSU are Web Application Development, Computer Networks, "
                     "Software Engineering, Cloud Computing, Introduction Database systems, Introduction to A.I., and "
                     "Unix/Linux System Admin.I was awarded Dr. Linda Wilkens and Dr. Glenn Pavlicek Scholarship at BSU in "
                     "recognition of my academic achievements such as a 4.0 major GPA. I am from East Greenwich, Road Island "
                     "but I currently live in Fairhaven, Massachusetts. Some programing languages that I am proficient at are"
                     " Python, Java, Swift, and JavaScript. I also MySQL from my database system course. Currently, I am "
                     "developing a bank statement processing application that efficiently converts bank statements into Excel"
                     " spreadsheets. With a positive attitude and a relentless motivation to learn, I'm eager to take on new "
                     "challenges and expand my expertise. Additionally, along with my current project, I am also doing a "
                     "research internship at Bridgewater State University in which I am developing a program that can "
                     "recognize a table in an image and convert it to an excel table. Some tools that I know are Git, "
                     "JetBrain IDEs, Xcode, and Vscode. My hobbies are playing basketball, cricket, and programing.")

    # Prepare the API request payload for Google's Gemini AI model
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={key}"
    headers = {'content-type': 'application/json'}
    data = {
        "contents": [{
            "parts": [{"text": f"Remember my Personal Information: {personal_info} \n Remember the Job description: "
                               f"{job_description} \n Now create a resume in markdown format that will be designed from "
                               f"my personal information, using keywords from job description that I provided"}]
        }]
    }

    # Send a post request to the Gemini API
    response = requests.post(url, headers=headers, json=data)
    response_json = response.json()

    # Extract the generated markdown resume from the API response
    marked_resume = response_json["candidates"][0]["content"]["parts"][0]["text"]

    # Save the generated resume to a markdown file
    new_file_name = "../Marked_Resume.md"
    with open(new_file_name, 'w') as f:
        f.write(marked_resume)


main()
